### ISSUE TITLE
[Feature Request] Example Terrain Presets

### ISSUE THREAD

**Issue by BoltsJ** [Wibble199/FoundryVTT-Terrain-Height-Tools#10]
It would be convenient to have one or two presets for terrain that could be loaded and customized to ease in setting up from scratch, examples of what is possible, or for users evaluating whether this module suits their needs. 

An idea for ux is that it could be a button that fills in the preset data to the text box. 

A possible bonus feature could be allowing systems to define their own presets by providing a path to a json file for THT to load as a preset via a hook or defined on the CONFIG global.

**Comment by Wibble199** [comment]
Thanks for the feature request. An 'Import Preset' button has now been added to the terrain config dialog in v0.3.4.

For now I've chosen not to add the ability for systems to define their own presets, to me it feels more like something that should be defined at the module level rather than the system level. I am happy to revisit this in future though if convinced otherwise.

**Comment by BoltsJ** [comment]
It looks like the ci workflow isn't adding the json file.
![image](https://github.com/user-attachments/assets/1ee28b42-2380-4b79-a1b1-feb24ff0e71c)

**Comment by Wibble199** [comment]
Thanks for spotting that, I never noticed. "It worked on my machine!". Should be fixed in v0.3.5.
